/**
 * C3 - explainable career guidance: typed access to the exported artefacts.
 *
 * `model/career-model.json` (taxonomy, role profiles, parameters) and
 * `model/knowledge-graph.json` (Gap-to-Action graph) are generated by
 * `python ml/c3/run_pipeline.py`; never edit them by hand. They are built from
 * SYNTHETIC job advertisements until real ads are collected, and every result the
 * runtime returns carries `syntheticTraining: true` while that is the case.
 */
import graphJson from "./model/knowledge-graph.json";
import modelJson from "./model/career-model.json";

export type Localised = { en: string; si: string; ta: string };

export type TaxonomySkill = { id: string; area: string; label: Localised; synonyms: string[] };

export type RoleSkill = {
  skillId: string;
  /** Normalised TF-IDF importance; the weights of one role add up to 1. */
  weight: number;
  /** Share of this role's ads that mention the skill ("nice to have" counts half). */
  tf: number;
  idf: number;
  /** Median level (1-3) the ads ask for. */
  requiredLevel: number;
  levelCounts: [number, number, number];
  adsMentioning: number;
};

export type RoleProfile = { id: string; label: Localised; adCount: number; skills: RoleSkill[] };

export type CareerModel = {
  schemaVersion: string;
  version: string;
  trainedOn: string;
  warning: string;
  generatedAt: string;
  params: {
    lambdaGapPenalty: number;
    minSupport: number;
    preferredMentionWeight: number;
    fuzzyThreshold: number;
    fuzzyMinChars: number;
  };
  adCorpus: { total: number; usedForProfiles: number; sourceType: string };
  taxonomy: {
    version: string;
    levels: Array<{ level: number; label: Localised }>;
    areas: Array<{ id: string; label: Localised }>;
    skills: TaxonomySkill[];
  };
  roles: RoleProfile[];
};

export type ActionType = "Module" | "Project" | "Certification" | "Resource";

export type GraphNode =
  | { id: string; type: "Skill" | "Role"; ref: string }
  | {
      id: string;
      type: ActionType;
      ref: string;
      title: string;
      description: string;
      effortHours: number;
      url?: string;
      provider?: string;
    };

export type GraphEdge =
  | { type: "requires"; from: string; to: string; weight: number; requiredLevel: number }
  | { type: "prerequisite_of"; from: string; to: string; minLevel: number }
  | { type: "teaches" | "evidences"; from: string; to: string; level: number };

export type KnowledgeGraph = {
  schemaVersion: string;
  modelVersion: string;
  provenance: string;
  planner: { maxGaps: number; maxStepsPerSkill: number };
  nodes: GraphNode[];
  edges: GraphEdge[];
};

export const careerModel = modelJson as unknown as CareerModel;
export const knowledgeGraph = graphJson as unknown as KnowledgeGraph;

export const SKILL_IDS: string[] = careerModel.taxonomy.skills.map((s) => s.id);
export const ROLE_IDS: string[] = careerModel.roles.map((r) => r.id);

const rolesById = new Map(careerModel.roles.map((r) => [r.id, r]));
const skillsById = new Map(careerModel.taxonomy.skills.map((s) => [s.id, s]));

export function getRole(id: string): RoleProfile | undefined {
  return rolesById.get(id);
}

export function getSkill(id: string): TaxonomySkill | undefined {
  return skillsById.get(id);
}

export const isSyntheticModel = /synthetic/i.test(careerModel.trainedOn);

export const careerModelInfo = {
  version: careerModel.version,
  trainedOn: careerModel.trainedOn,
  warning: careerModel.warning,
  taxonomyVersion: careerModel.taxonomy.version,
  roleCount: careerModel.roles.length,
  skillCount: careerModel.taxonomy.skills.length,
  adsUsed: careerModel.adCorpus.usedForProfiles,
  syntheticTraining: isSyntheticModel
};
